logsBucket: 'gs://buildlogs-1qaz'
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/akerekes-gcf-sandbox/cloudruncd', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/akerekes-gcf-sandbox/cloudruncd']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloudruntest', '--image', 'gcr.io/akerekes-gcf-sandbox/cloudruncd1', '--region', 'us-central1']
images:
- gcr.io/akerekes-gcf-sandbox/cloudruncd
