options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: akerekes-gcf-sandbox
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['alpha', 'run', 'deploy', 'cloudruntest', '--region', 'us-central1', '--source', '.', '--function', 'helloWorld']
